# Generated by Django 5.0.6 on 2024-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='addressbookentry',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
