# Generated by Django 5.0.6 on 2024-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_addressbookentry_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookentry',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
