# Generated by Django 5.0.6 on 2024-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_addressbookentry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookentry',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
