# Generated by Django 5.0.6 on 2024-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_addressbookentry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookentry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addressbookentry',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
